### ISSUE TITLE
a-10 kind of cheese but moreso a speed strat

### ISSUE THREAD

**Issue by caeyo** [tyler-t-software/Mirage-Rock-Playtesting#35]
diagonal through and jump and you can skip the third dream block - double jump makes it much easier, it's harder to make it with a single jump. don't know if it's worth patching cause it doesn't make the room easier, it just makes it faster, and it's pretty cool - you could try and limit it so that it's only possible with double jump cause then it's definitely just a speedrun thing but up to you
https://gfycat.com/flippantorderlyamericanbadger

**Comment by bissy-bissy-bissy** [comment]
Yeah I kind of consider most cheese involving double jump dream block stuff things I don't care a lot about, this is an easy room so I'm fine with people doing it multiple ways, including not even double jump
