### ISSUE TITLE
b-04 hard to read/overly tight

### ISSUE THREAD

**Issue by xaviershrier** [tyler-t-software/Mirage-Rock-Playtesting#41]
Figuring out that you need to dash down after the large dream block was really hard, and might have been helped by a bino, + the gap to get into the top right dreamblock is too tight - widening it by a tile or so would probably fix this

**Comment by bissy-bissy-bissy** [comment]
Widened the top right dream block, however I don't want to add a bino to this room since I feel like it should be sightreadable. I tried instead to make the down dash more intuitive by tightening the gap.
