### ISSUE TITLE
b-00 feels kind of empty?

### ISSUE THREAD

**Issue by caeyo** [tyler-t-software/Mirage-Rock-Playtesting#9]
this is kind of a big room where a berry used to be (a good one at that ):<) but it's very basic for its size, it's literally just through a dream block and take a move block upwards - it needs something else cause it feels out of place
<img width="1792" alt="Screen Shot 2020-10-02 at 4 37 13 pm" src="https://user-images.githubusercontent.com/72244655/94894967-c2ec3980-04cd-11eb-86c2-8a90d6dabc4c.png">

**Comment by bissy-bissy-bissy** [comment]
I've removed this berry for the following reasons:

1) I feel like it's awkward to use a move block as you go into a fake wall, when you go into it you don't 100% know if you're even going to be right, so initially going through with it is just so weird
2) The berry's gameplay itself is not even that enticing, it was just this lame thing where you went through a tight tunnel, the only cool part was that you fell down at the end
3) This is going to be a checkpoint with dialog, so I think it doesn't need gameplay (Like the room with the very first move block? That's also dialog); the room not having gameplay is not an issue in my opinion.

caeyo agreed with these points, therefore this will be closed.
